"""
Synthetic ground-truth fixtures for the Waterflood Optimizer validation suite (Architecture §16 Tier 1).

Each case is generated by forward-simulating the CRM material balance with KNOWN parameters
(f_ij, tau_j, J_j, oil-cut model), so the app's history-match can be scored against truth.

Cases
  streak_5x4        5 inj x 4 prod, one high-permeability streak I3->P4; noise-free + 5% noise
  aquifer_6x9       6 inj x 9 prod, Fetkovich finite aquifer supporting the flank producers
  converted_wells   6 wells; P-02 and P-05 converted producer->injector at month 48
  allocated_noisy   streak field with monthly allocation noise (8%), days-on, shut-ins, ESP events
  sectored_60       60 wells in two sealed sectors (no cross-sector connectivity), for runtime tests

Outputs per case (folder <case>/):
  rates.csv, pressure.csv, coords.csv, category.csv, truth.json, README.md
"""

import json
import math
import os

import numpy as np

OUT = os.path.dirname(os.path.abspath(__file__))
os.makedirs(OUT, exist_ok=True)
rng = np.random.default_rng(42)


# ---------------------------------------------------------------- helpers
def month_dates(n, start=(2016, 1)):
    y, m = start
    out = []
    for _ in range(n):
        out.append(f"{y:04d}-{m:02d}-01")
        m += 1
        if m > 12:
            m = 1
            y += 1
    return out


def days_in(date):
    y, m = int(date[:4]), int(date[5:7])
    return [
        31,
        29 if (y % 4 == 0 and (y % 100 != 0 or y % 400 == 0)) else 28,
        31,
        30,
        31,
        30,
        31,
        31,
        30,
        31,
        30,
        31,
    ][m - 1]


def inj_signal(n, base, amp, period, phase, seed):
    """Rich, injector-specific signal: sinusoid + piecewise-constant operating levels + short shut-ins + noise."""
    r = np.random.default_rng(seed)
    t = np.arange(n)
    s = base + amp * np.sin(2 * np.pi * t / period + phase)
    # piecewise-constant levels changing at injector-specific times (4-7 changes)
    for k in np.sort(r.integers(6, n - 6, r.integers(4, 8))):
        s[k:] += r.uniform(-0.2, 0.2) * base
    # two short shut-ins (1-2 months)
    for k in r.integers(8, n - 8, 2):
        s[k : k + int(r.integers(1, 3))] = 0.0
    s += 0.08 * amp * r.standard_normal(n)
    return np.clip(s, 0.0, None)


def crm_forward(inj, F, tau, q0, dt=1.0, bhp=None, J=None):
    """inj: (n, Ni); F: (Ni, Np); tau: (Np,). Returns total liquid q: (n, Np) in reservoir bbl/d.
    Discrete superposition solution (Sayarpour et al. 2009), optional BHP term."""
    n, Ni = inj.shape
    Np = F.shape[1]
    q = np.zeros((n, Np))
    q[0] = q0
    e = np.exp(-dt / tau)
    for t in range(1, n):
        steady = inj[t] @ F
        q[t] = q[t - 1] * e + steady * (1 - e)
        if bhp is not None and J is not None:
            q[t] -= J * (bhp[t] - bhp[t - 1]) * e  # producer BHP change term
    return q


def oil_cut(cwi, alpha, beta):
    return 1.0 / (1.0 + alpha * np.power(np.maximum(cwi, 1.0), beta))


def write_case(
    name,
    dates,
    inj_names,
    prod_names,
    inj,
    qliq,
    fo,
    coords,
    cat,
    truth,
    readme,
    bhp=None,
    days_on=None,
    alloc_noise=0.0,
    prod_noise=0.0,
    extra_events=None,
    role_table=None,
    inj_names_by_month=None,
):
    d = os.path.join(OUT, name)
    os.makedirs(d, exist_ok=True)
    n = len(dates)
    Bo, Bw = truth["pvt"]["Bo"], truth["pvt"]["Bw"]
    rows = ["well_id,date,type,q_oil,q_water,q_gas,q_inj,days_on"]
    r = np.random.default_rng(7)
    for t, dt_ in enumerate(dates):
        dim = days_in(dt_)
        for i, w in enumerate(inj_names):
            if inj_names_by_month is not None and not inj_names_by_month[t][i]:
                continue
            don = dim if days_on is None else days_on[t][("I", i)]
            v = inj[t, i] / Bw * (1 + alloc_noise * r.standard_normal())
            rows.append(f"{w},{dt_},INJ,,,,{max(v, 0) * don / dim:.1f},{don}")
        for j, w in enumerate(prod_names):
            if role_table is not None and not role_table[t][j]:
                continue
            don = dim if days_on is None else days_on[t][("P", j)]
            ql = qliq[t, j]
            qo = ql * fo[t, j] / Bo
            qw = ql * (1 - fo[t, j]) / Bw
            qo *= 1 + prod_noise * r.standard_normal()
            qw *= 1 + prod_noise * r.standard_normal()
            rows.append(
                f"{w},{dt_},PROD,{max(qo, 0) * don / dim:.1f},{max(qw, 0) * don / dim:.1f},{max(qo, 0) * 350 * don / dim:.0f},,{don}"
            )
    open(os.path.join(d, "rates.csv"), "w").write("\n".join(rows) + "\n")

    prow = ["well_id,date,bhp,whp,source"]
    if bhp is not None:
        for t, dt_ in enumerate(dates):
            for j, w in enumerate(prod_names):
                if role_table is not None and not role_table[t][j]:
                    continue
                prow.append(f"{w},{dt_},{bhp[t, j]:.0f},{bhp[t, j] * 0.18:.0f},ESP")
    open(os.path.join(d, "pressure.csv"), "w").write("\n".join(prow) + "\n")

    crow = ["well_id,x,y,tvd"] + [
        f"{w},{x:.1f},{y:.1f},{tvd:.0f}" for w, (x, y, tvd) in coords.items()
    ]
    open(os.path.join(d, "coords.csv"), "w").write("\n".join(crow) + "\n")
    krow = ["well_id,field,reservoir,block"] + [
        f"{w},{f},{res},{b}" for w, (f, res, b) in cat.items()
    ]
    open(os.path.join(d, "category.csv"), "w").write("\n".join(krow) + "\n")
    if extra_events:
        erow = ["well_id,date,type,note"] + [
            f"{w},{dt_},{ty},{note}" for w, dt_, ty, note in extra_events
        ]
        open(os.path.join(d, "events.csv"), "w").write("\n".join(erow) + "\n")
    json.dump(truth, open(os.path.join(d, "truth.json"), "w"), indent=1)
    open(os.path.join(d, "README.md"), "w").write(readme)
    print(f"{name}: {len(rows) - 1} rate rows, {len(prow) - 1} pressure rows")


PVT = {"Bo": 1.25, "Bw": 1.02, "ct_per_psi": 1.2e-5, "mu_o_cp": 1.8, "mu_w_cp": 0.5}


# ================================================================ streak_5x4
def build_streak(name, noise, alloc=0.0, days_on_mode=False, events=False):
    n = 120
    dates = month_dates(n)
    inj_names = [f"I-{k}" for k in range(1, 6)]
    prod_names = [f"P-{k}" for k in range(1, 5)]
    coords = {
        "I-1": (1000, 1000, 2510),
        "I-2": (1000, 3000, 2520),
        "I-3": (3000, 2000, 2505),
        "I-4": (5000, 1000, 2515),
        "I-5": (5000, 3000, 2500),
        "P-1": (2000, 1500, 2508),
        "P-2": (2000, 2500, 2512),
        "P-3": (4000, 1500, 2503),
        "P-4": (4000, 2500, 2518),
    }
    cat = {w: ("ALPHA", "A-SAND", "BLK-1") for w in coords}
    # true allocation: distance based, plus a streak I-3 -> P-4
    F = np.zeros((5, 4))
    for i, wi in enumerate(inj_names):
        for j, wj in enumerate(prod_names):
            d = math.dist(coords[wi][:2], coords[wj][:2])
            F[i, j] = 1 / d**2
    F[2, 3] *= 6.0  # streak
    F = (
        F / F.sum(axis=1, keepdims=True) * np.array([0.92, 0.90, 0.95, 0.88, 0.93])[:, None]
    )  # some loss to boundary
    tau = np.array([28.0, 35.0, 22.0, 9.0])  # P-4 fast because of the streak
    J = np.array([1.1, 0.9, 1.3, 1.6])
    inj = np.column_stack(
        [inj_signal(n, 1500 + 150 * k, 350, 14 + 3 * k, 0.7 * k, 100 + k) for k in range(5)]
    )
    bhp = np.column_stack(
        [1600 - 0.4 * np.arange(n) + 25 * np.sin(np.arange(n) / 9 + j) for j in range(4)]
    )
    if events:  # ESP frequency steps as BHP steps
        bhp[60:, 1] -= 120
        bhp[85:, 3] += 90
    qliq = crm_forward(inj, F, tau, q0=np.array([900, 850, 1000, 1100.0]), bhp=bhp, J=J)
    cwi = np.cumsum(qliq, axis=0) * 30
    alpha, beta = np.array([2.5e-7, 3e-7, 2e-7, 4e-7]), np.array([1.5, 1.55, 1.5, 1.6])
    fo = oil_cut(cwi, alpha, beta)
    days = None
    ev = None
    if days_on_mode:
        r = np.random.default_rng(3)
        days = []
        for t, dt_ in enumerate(dates):
            dim = days_in(dt_)
            m = {}
            for i in range(5):
                m[("I", i)] = 0 if r.random() < 0.03 else int(dim - r.integers(0, 3))
            for j in range(4):
                m[("P", j)] = 0 if r.random() < 0.04 else int(dim - r.integers(0, 3))
            days.append(m)
        ev = [
            ("P-2", dates[60], "ESP_FREQ", "frequency 52->58 Hz"),
            ("P-4", dates[85], "CHOKE", "choke 40->32/64"),
            ("I-3", dates[40], "WORKOVER", "acid stimulation"),
        ]
    truth = {
        "case": name,
        "n_months": n,
        "injectors": inj_names,
        "producers": prod_names,
        "f_ij": {
            inj_names[i]: {prod_names[j]: round(float(F[i, j]), 4) for j in range(4)}
            for i in range(5)
        },
        "tau_days": dict(zip(prod_names, tau.tolist())),
        "J_bbl_d_psi": dict(zip(prod_names, J.tolist())),
        "oilcut": {"model": "power_law_WOR_CWI", "alpha": alpha.tolist(), "beta": beta.tolist()},
        "streak": "I-3 -> P-4 (f=%.2f, tau_P4=9 d)" % F[2, 3],
        "pvt": PVT,
        "bhp_available": True,
        "noise": {"production_pct": noise * 100, "allocation_pct": alloc * 100},
        "expected_tournament_winner": "CRMP",
        "expected_runner_up": "CRMIP",
        "acceptance": {
            "streak_pair_must_be_largest_f_into_P4": True,
            "tau_tolerance_pct": 20 if noise == 0 else 35,
            "blind_MAPE_max_pct": 1.5 if noise == 0 else 7,
            "note": "blind R2 is informational only when noise ~ signal variance in the blind window; evaluate on producing days (days_on>0) with per-producing-day rates",
        },
        "optimizer_check": {
            "note": "moving water from I-1/I-2 toward I-3 should raise oil; proportional->optimized gain expected 6-12% over 12 months at constant total injection"
        },
    }
    rd = f"# {name}\n\n5 injectors, 4 producers, 120 monthly steps, one high-permeability streak I-3 -> P-4.\nGenerated by CRM forward model with BHP term. Truth in truth.json.\n\nProduction noise {noise * 100:.0f}%, allocation noise {alloc * 100:.0f}%.\n"
    write_case(
        name,
        dates,
        inj_names,
        prod_names,
        inj,
        qliq,
        fo,
        coords,
        cat,
        truth,
        rd,
        bhp=bhp,
        days_on=days,
        alloc_noise=alloc,
        prod_noise=noise,
        extra_events=ev,
    )


build_streak("streak_5x4_clean", noise=0.0)
build_streak("streak_5x4_noisy", noise=0.05)
build_streak("allocated_noisy", noise=0.05, alloc=0.08, days_on_mode=True, events=True)


# ================================================================ aquifer_9x9
def build_aquifer():
    name = "aquifer_9x9"
    n = 160
    dates = month_dates(n)
    inj_names = [f"I-{k}" for k in range(1, 10)]
    prod_names = [f"P-{k}" for k in range(1, 10)]
    coords = {}
    for k in range(9):
        coords[f"I-{k + 1}"] = (1000 + (k % 3) * 2000, 1800 + (k // 3) * 2000, 2600)
    for k in range(9):
        coords[f"P-{k + 1}"] = (
            2000 + (k % 3) * 2000,
            900 + (k // 3) * 2000,
            2600,
        )  # P-1..P-3 = southern flank, nearest the aquifer
    cat = {w: ("BRAVO", "B-SAND", "BLK-9") for w in coords}
    F = np.zeros((9, 9))
    for i, wi in enumerate(inj_names):
        for j, wj in enumerate(prod_names):
            d = math.dist(coords[wi][:2], coords[wj][:2])
            F[i, j] = 1 / d**2 if d < 4500 else 0.0
    # column-target normalisation: interior producers receive Σ_i f_ij = 0.95, flank (P-1..P-3) only 0.45;
    # then cap any injector row at 0.95 so no injector delivers more than 95 % of its water.
    target = np.array([0.6, 0.6, 0.6] + [0.95] * 6)
    F = F / np.maximum(F.sum(axis=0, keepdims=True), 1e-12) * target
    rs = F.sum(axis=1, keepdims=True)
    F = np.where(rs > 0.95, F * 0.95 / rs, F)
    tau = np.array([40, 45, 38, 50, 42, 36, 60, 55, 48.0])
    inj = np.column_stack(
        [inj_signal(n, 1300 + 80 * k, 320, 16 + 2 * k, 0.5 * k, 200 + k) for k in range(9)]
    )
    qbase = crm_forward(inj, F, tau, q0=np.full(9, 700.0))
    # Fetkovich finite aquifer: sized so influx ~ 0.9x the injection-derived flank rate at start, declining
    cap_r, ratio, Jaq = 900.0, 6.0, 10.0
    pr, paq = 3000.0, 3350.0
    We = np.zeros(n)
    for t in range(n):
        We_dot = max(Jaq * (paq - pr), 0.0)
        We[t] = We_dot
        pr += (We_dot + inj[t].sum() - qbase[t].sum() - We_dot) / (
            cap_r * 40
        )  # reservoir pressure ~maintained by injection
        paq -= We_dot / (cap_r * ratio)
    aq_alloc = np.array([0.36, 0.34, 0.30, 0, 0, 0, 0, 0, 0.0])
    qliq = crm_forward(
        np.column_stack([inj, We]), np.vstack([F, aq_alloc]), tau, q0=np.full(9, 700.0)
    )
    cwi = np.cumsum(qliq, axis=0) * 30
    fo = oil_cut(cwi, np.full(9, 2.2e-7), np.full(9, 1.45))
    fo[:, :3] *= 0.85
    bhp = np.column_stack(
        [1500 - 0.4 * np.arange(n) + 25 * np.sin(np.arange(n) / 11 + j) for j in range(9)]
    )
    flank_inj_sum = {prod_names[j]: float(F[:, j].sum()) for j in range(3)}
    truth = {
        "case": name,
        "n_months": n,
        "injectors": inj_names,
        "producers": prod_names,
        "f_ij": {
            inj_names[i]: {prod_names[j]: round(float(F[i, j]), 4) for j in range(9) if F[i, j] > 0}
            for i in range(9)
        },
        "injection_only_sum_f_per_producer": {
            prod_names[j]: round(float(F[:, j].sum()), 3) for j in range(9)
        },
        "aquifer": {
            "model": "Fetkovich_finite",
            "J_aq_bbl_d_psi": Jaq,
            "PV_ratio_aquifer_to_reservoir": ratio,
            "initial_p_aq_psi": 3320,
            "initial_p_res_psi": 3000,
            "allocation_to_producers": dict(zip(prod_names, aq_alloc.tolist())),
            "influx_bbl_d_start": float(We[0]),
            "influx_bbl_d_end": float(We[-1]),
        },
        "tau_days": dict(zip(prod_names, tau.tolist())),
        "pvt": PVT,
        "bhp_available": True,
        "signature": "CRMP without aquifer must inflate sum_i f_ij for P-1..P-3 well above the interior producers (apparent sum > 1.15 or > 1.6x interior median)",
        "expected_tournament_winner": "CRM-Aquifer (CRMPA)",
        "expected_excluded": ["two-phase (water cut>0.5 after month ~40)"],
        "acceptance": {
            "flank_apparent_sum_f_min": 1.15,
            "flank_over_interior_median_ratio_min": 1.3,
            "interior_apparent_sum_f_max": 1.05,
            "influx_tolerance_pct": 30,
            "blind_MAPE_max_pct": 6,
        },
    }
    rd = f"# {name}\n\n9 injectors, 9 producers, 160 months. Finite Fetkovich aquifer supports the southern flank P-1..P-3, which injection alone under-supplies.\nThe app must detect the influx signature and select the aquifer variant.\n"
    write_case(
        name,
        dates,
        inj_names,
        prod_names,
        inj,
        qliq,
        fo,
        coords,
        cat,
        truth,
        rd,
        bhp=bhp,
        prod_noise=0.04,
    )


build_aquifer()


# ================================================================ converted_wells
def build_converted():
    name = "converted_wells"
    n = 96
    dates = month_dates(n)
    conv = 48
    wells = ["I-1", "I-2", "P-1", "P-2", "P-3", "P-4", "P-5"]
    coords = {
        "I-1": (1000, 2000, 2400),
        "I-2": (5000, 2000, 2410),
        "P-1": (2000, 1000, 2405),
        "P-2": (2000, 3000, 2402),
        "P-3": (3000, 2000, 2408),
        "P-4": (4000, 1000, 2404),
        "P-5": (4000, 3000, 2406),
    }
    cat = {w: ("ALPHA", "A-SAND", "BLK-2") for w in coords}

    # phase A (months 0-47): injectors I-1,I-2 ; producers P-1..P-5
    # phase B (48-95): P-2 and P-5 converted to injectors -> injectors I-1,I-2,P-2,P-5 ; producers P-1,P-3,P-4
    def Fmat(injs, prods, boost=None):
        F = np.zeros((len(injs), len(prods)))
        for i, wi in enumerate(injs):
            for j, wj in enumerate(prods):
                F[i, j] = 1 / math.dist(coords[wi][:2], coords[wj][:2]) ** 2
        return F / F.sum(axis=1, keepdims=True) * 0.9

    injA = ["I-1", "I-2"]
    prodA = ["P-1", "P-2", "P-3", "P-4", "P-5"]
    injB = ["I-1", "I-2", "P-2", "P-5"]
    prodB = ["P-1", "P-3", "P-4"]
    FA = Fmat(injA, prodA)
    FB = Fmat(injB, prodB)
    tauA = np.array([30, 32, 25, 31, 33.0])
    tauB = np.array([26, 20, 27.0])
    sig = np.column_stack(
        [
            inj_signal(n, 1800, 400, 15, 0, 300),
            inj_signal(n, 1700, 380, 18, 1, 301),
            inj_signal(n, 900, 200, 13, 2, 302),
            inj_signal(n, 950, 220, 17, 3, 303),
        ]
    )
    qA = crm_forward(sig[:conv, :2], FA, tauA, q0=np.full(5, 600.0))
    qB = crm_forward(sig[conv:, :], FB, tauB, q0=np.array([qA[-1, 0], qA[-1, 2], qA[-1, 3]]))
    # assemble per-well series in canonical well order (all 7 wells as both possible roles)
    inj_all = np.zeros((n, 4))
    inj_all[:conv, :2] = sig[:conv, :2]
    inj_all[conv:, :] = sig[conv:, :]
    qliq = np.zeros((n, 5))
    qliq[:conv] = qA
    qliq[conv:, [0, 2, 3]] = qB
    cwi = np.cumsum(qliq, axis=0) * 30
    fo = oil_cut(cwi, np.full(5, 3e-7), np.full(5, 1.5))
    inj_names = ["I-1", "I-2", "P-2", "P-5"]
    prod_names = prodA
    inj_by_month = [[True, True, t >= conv, t >= conv] for t in range(n)]
    role = [[True, t < conv, True, True, t < conv] for t in range(n)]
    bhp = np.column_stack(
        [1550 - 2 * np.arange(n) + 25 * np.sin(np.arange(n) / 10 + j) for j in range(5)]
    )
    truth = {
        "case": name,
        "n_months": n,
        "conversion_month_index": conv,
        "conversion_date": dates[conv],
        "converted_wells": {"P-2": "producer->injector", "P-5": "producer->injector"},
        "expected_well_types": {
            "I-1": "INJ",
            "I-2": "INJ",
            "P-1": "PROD",
            "P-3": "PROD",
            "P-4": "PROD",
            "P-2": "MIXED",
            "P-5": "MIXED",
        },
        "phase_A": {
            "injectors": injA,
            "producers": prodA,
            "f_ij": {
                injA[i]: {prodA[j]: round(float(FA[i, j]), 4) for j in range(5)} for i in range(2)
            },
            "tau_days": dict(zip(prodA, tauA.tolist())),
        },
        "phase_B": {
            "injectors": injB,
            "producers": prodB,
            "f_ij": {
                injB[i]: {prodB[j]: round(float(FB[i, j]), 4) for j in range(3)} for i in range(4)
            },
            "tau_days": dict(zip(prodB, tauB.tolist())),
        },
        "pvt": PVT,
        "bhp_available": True,
        "expected_behaviour": "loader derives MIXED with conversion at 2020-01; engine splits history at that date and fits two windows",
        "acceptance": {
            "well_type_exact": True,
            "window_split_exact": True,
            "phase_B_f_ij_tolerance_pct": 15,
        },
    }
    rd = f"# {name}\n\nP-2 and P-5 convert from producer to injector at {dates[conv]}. Tests well-type derivation, role splitting and window segmentation.\n"
    write_case(
        name,
        dates,
        inj_names,
        prod_names,
        inj_all,
        qliq,
        fo,
        coords,
        cat,
        truth,
        rd,
        bhp=bhp,
        prod_noise=0.03,
        role_table=role,
        inj_names_by_month=inj_by_month,
        extra_events=[
            ("P-2", dates[conv], "CONVERSION", "producer to injector"),
            ("P-5", dates[conv], "CONVERSION", "producer to injector"),
        ],
    )


build_converted()


# ================================================================ sectored_60
def build_sectored():
    name = "sectored_60"
    n = 96
    dates = month_dates(n)
    coords = {}
    cat = {}
    inj_names = []
    prod_names = []
    for s, (sx, sy, blk) in enumerate([(0, 0, "SEC-N"), (12000, 0, "SEC-S")]):
        for k in range(30):
            x = sx + 1000 + (k % 6) * 1600
            y = sy + 1000 + (k // 6) * 1400
            w = f"I-{s + 1}{k:02d}" if (k % 6 + k // 6) % 2 == 0 else f"P-{s + 1}{k:02d}"
            coords[w] = (x, y, 2700 + s * 40)
            cat[w] = ("CHARLIE", "C-SAND", blk)
            (inj_names if w.startswith("I") else prod_names).append(w)
    Ni, Np = len(inj_names), len(prod_names)
    F = np.zeros((Ni, Np))
    for i, wi in enumerate(inj_names):
        for j, wj in enumerate(prod_names):
            if cat[wi][2] != cat[wj][2]:
                continue  # sealed sectors
            d = math.dist(coords[wi][:2], coords[wj][:2])
            if d > 3500:
                continue  # local connectivity only
            F[i, j] = 1 / d**2
    F = F / np.maximum(F.sum(axis=1, keepdims=True), 1e-12) * 0.9
    tau = rng.uniform(15, 60, Np)
    J = rng.uniform(0.6, 1.6, Np)
    inj = np.column_stack(
        [inj_signal(n, 1200 + 50 * (k % 7), 300, 12 + k % 9, 0.3 * k, 400 + k) for k in range(Ni)]
    )
    bhp = np.column_stack(
        [1500 - 1.5 * np.arange(n) + 30 * np.sin(np.arange(n) / 9 + j) for j in range(Np)]
    )
    qliq = crm_forward(inj, F, tau, q0=np.full(Np, 600.0), bhp=bhp, J=J)
    cwi = np.cumsum(qliq, axis=0) * 30
    fo = oil_cut(cwi, np.full(Np, 2.5e-7), np.full(Np, 1.5))
    truth = {
        "case": name,
        "n_months": n,
        "injectors": inj_names,
        "producers": prod_names,
        "sectors": {"SEC-N": "x<9000", "SEC-S": "x>=9000"},
        "f_ij": {
            inj_names[i]: {
                prod_names[j]: round(float(F[i, j]), 4) for j in range(Np) if F[i, j] > 0
            }
            for i in range(Ni)
        },
        "tau_days": dict(zip(prod_names, tau.round(1).tolist())),
        "pvt": PVT,
        "bhp_available": True,
        "expected_behaviour": "sectorization must recover two sectors; any cross-sector f_ij > 0.05 is a failure; full tournament < 10 min on 8 cores",
        "acceptance": {
            "cross_sector_f_ij_max": 0.05,
            "runtime_minutes_max": 10,
            "blind_MAPE_max_pct": 6,
            "note": "dense local connectivity makes individual f_ij non-unique without sparsity/distance prior; score sector recovery and MAPE, not per-pair f_ij",
        },
    }
    rd = f"# {name}\n\n60 wells ({Ni} injectors, {Np} producers) in two sealed sectors, 84 months. Runtime and sectorization test.\n"
    write_case(
        name,
        dates,
        inj_names,
        prod_names,
        inj,
        qliq,
        fo,
        coords,
        cat,
        truth,
        rd,
        bhp=bhp,
        prod_noise=0.03,
    )


build_sectored()

open(
    os.path.join(OUT, "README.md"), "w"
).write("""# Synthetic validation fixtures — Waterflood Optimizer (§16 Tier 1)

| case | wells | months | tests |
|---|---|---|---|
| streak_5x4_clean | 5 inj / 4 prod | 120 | parameter recovery (f_ij ±10 %, tau ±20 %), blind R² ≥ 0.9 |
| streak_5x4_noisy | same | 120 | robustness to 5 % production noise |
| allocated_noisy | same + days-on, shut-ins, ESP/choke events | 120 | QC layer, event windowing, allocation noise 8 % |
| aquifer_9x9 | 9 / 9 | 160 | influx signature detection, CRM-Aquifer selection, PV & influx recovery |
| converted_wells | 2 inj + 5 prod, 2 converted | 96 | MIXED well-type derivation, role split, window segmentation |
| sectored_60 | 60 | 96 | sectorization, no cross-sector connectivity, runtime < 10 min |

All rates are surface volumes (bbl/d averaged over the month, scaled by days_on) generated from a CRM forward
model in reservoir volumes with Bo=1.25, Bw=1.02. Convert back to reservoir volumes before fitting.
Each folder: rates.csv, pressure.csv (ESP-style flowing BHP), coords.csv, category.csv, truth.json, optional events.csv.
Column names match the app's canonical schema so the loader auto-maps them; rename columns to test mapping.
""")
print("done")
